apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-deploy
  name: db-deploy
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30002
  selector:
    app: db-deploy
  type: NodePort
